@extends('layouts.app')
@section('title','مدیران')
@section('page-heading','مدیریت مدیران')
@section('content')
<div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">مدیران</h1><p class="text-muted mb-0">مدیریت دسترسی کاربران پنل</p></div><a href="{{ route('admins.create') }}" class="btn btn-primary"><i class="bi bi-person-plus ms-1"></i>مدیر جدید</a></div>
<div class="card"><div class="card-body border-bottom"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="جستجو در نام یا موبایل..."></div><div class="col-auto"><button class="btn btn-outline-primary">جستجو</button></div>@if(request('search'))<div class="col-auto"><a class="btn btn-light" href="{{ route('admins.index') }}">پاک کردن</a></div>@endif</form></div>
<div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'name','direction'=>$sort==='name'&&$direction==='asc'?'desc':'asc']) }}">نام <i class="bi bi-arrow-down-up"></i></a></th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'mobile','direction'=>$sort==='mobile'&&$direction==='asc'?'desc':'asc']) }}">شماره موبایل <i class="bi bi-arrow-down-up"></i></a></th><th>وضعیت</th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'created_at','direction'=>$sort==='created_at'&&$direction==='asc'?'desc':'asc']) }}">تاریخ ایجاد <i class="bi bi-arrow-down-up"></i></a></th><th class="text-start">عملیات</th></tr></thead><tbody>
@forelse($admins as $admin)<tr><td class="fw-semibold">{{ $admin->name }} @if(auth()->id()===$admin->id)<span class="badge bg-primary-subtle text-primary">شما</span>@endif</td><td dir="ltr" class="text-end">{{ $admin->mobile }}</td><td><span class="badge bg-{{ $admin->is_active ? 'success' : 'secondary' }}-subtle text-{{ $admin->is_active ? 'success' : 'secondary' }}">{{ $admin->is_active ? 'فعال' : 'غیرفعال' }}</span></td><td>{{ $admin->created_at->format('Y/m/d H:i') }}</td><td class="text-start"><a href="{{ route('admins.edit',$admin) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a><form class="d-inline" method="POST" action="{{ route('admins.destroy',$admin) }}" data-confirm="این مدیر برای همیشه حذف می‌شود.">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" @disabled(auth()->id()===$admin->id)><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="5" class="text-center py-5 text-muted">موردی یافت نشد.</td></tr>@endforelse
</tbody></table></div>@if($admins->hasPages())<div class="card-footer bg-white pt-3">{{ $admins->links() }}</div>@endif</div>
@endsection
