@php($editing = isset($product))
<div class="row g-3">
    <div class="col-md-6"><label class="form-label required" for="title">عنوان محصول</label><input id="title" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title',$product->title ?? '') }}"><x-field-error name="title" /></div>
    <div class="col-md-6"><label class="form-label required" for="category_id">دسته اصلی</label><select id="category_id" name="category_id" class="form-select @error('category_id') is-invalid @enderror"><option value="">انتخاب کنید</option>@foreach($categoryOptions as $id=>$label)<option value="{{ $id }}" @selected((string)old('category_id',$product->category_id ?? '')===(string)$id)>{{ $label }}</option>@endforeach</select><x-field-error name="category_id" />@if($editing)<div class="form-text">با تغییر دسته، یک کد جدید از شمارنده دسته مقصد تولید می‌شود.</div>@endif</div>
    <div class="col-md-3"><label class="form-label" for="weight">وزن (گرم)</label><input dir="ltr" type="number" step="0.001" min="0" id="weight" name="weight" class="form-control @error('weight') is-invalid @enderror" value="{{ old('weight',$product->weight ?? '') }}"><x-field-error name="weight" /></div>
    <div class="col-md-3"><label class="form-label required" for="availability">وضعیت موجودی</label><select id="availability" name="availability" class="form-select @error('availability') is-invalid @enderror"><option value="available" @selected(old('availability',$product->availability ?? 'available')==='available')>موجود</option><option value="unavailable" @selected(old('availability',$product->availability ?? '')==='unavailable')>ناموجود</option></select><x-field-error name="availability" /></div>
    <div class="col-md-6"><label class="form-label" for="wage_percentage">اجرت درصدی</label><div class="input-group"><input dir="ltr" type="number" step="0.01" min="0" max="100" id="wage_percentage" name="wage_percentage" class="form-control @error('wage_percentage') is-invalid @enderror" value="{{ old('wage_percentage',$product->wage_percentage ?? '') }}"><span class="input-group-text">٪</span></div><x-field-error name="wage_percentage" /></div>
    <div class="col-12"><label class="form-label" for="short_description">توضیحات کوتاه</label><textarea id="short_description" name="short_description" rows="2" class="form-control @error('short_description') is-invalid @enderror">{{ old('short_description',$product->short_description ?? '') }}</textarea><x-field-error name="short_description" /></div>
    <div class="col-md-6"><label class="form-label {{ $editing ? '' : 'required' }}" for="main_image">تصویر اصلی</label><input type="file" accept="image/jpeg,image/png,image/webp" id="main_image" name="main_image" class="form-control @error('main_image') is-invalid @enderror"><x-field-error name="main_image" />@if($editing && $product->main_image)<div class="mt-2 d-flex align-items-center gap-2"><img class="thumb" src="{{ '/storage/'.ltrim($product->main_image, '/') }}" alt=""><input type="hidden" name="remove_main_image" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="remove_main_image" value="1" id="remove_main_image"><label class="form-check-label" for="remove_main_image">حذف تصویر فعلی</label></div></div>@endif</div>
    <div class="col-md-6"><label class="form-label" for="gallery">گالری (حداکثر ۳ تصویر)</label><input type="file" multiple accept="image/jpeg,image/png,image/webp" id="gallery" name="gallery[]" class="form-control @error('gallery') is-invalid @enderror"><x-field-error name="gallery" />@error('gallery.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    @if($editing && $product->images->isNotEmpty())<div class="col-12"><div class="d-flex gap-3 flex-wrap">@foreach($product->images as $image)<label class="border rounded p-2 text-center"><img src="{{ '/storage/'.ltrim($image->path, '/') }}" alt="" style="width:100px;height:100px;object-fit:cover" class="rounded d-block mb-2"><input class="form-check-input" type="checkbox" name="remove_gallery[]" value="{{ $image->id }}" @checked(in_array($image->id,old('remove_gallery',[])))> <small>حذف</small></label>@endforeach</div><x-field-error name="remove_gallery" /></div>@endif
</div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary">ذخیره محصول</button><a class="btn btn-light" href="{{ route('products.index') }}">انصراف</a></div>
