@extends('layouts.app') @section('title','محصولات') @section('page-heading','مدیریت محصولات')
@section('content')
<div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">محصولات</h1><p class="text-muted mb-0">مدیریت موجودی و اطلاعات محصولات</p></div><a href="{{ route('products.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg ms-1"></i>محصول جدید</a></div>
<div class="card"><div class="card-body border-bottom"><form class="row g-2 align-items-end"><div class="col-lg-4"><label class="form-label">جستجو</label><input class="form-control" name="search" value="{{ request('search') }}" placeholder="عنوان یا کد محصول..."></div><div class="col-md-3"><label class="form-label">دسته</label><select class="form-select" name="category_id"><option value="">همه دسته‌ها</option>@foreach($categoryOptions as $id=>$label)<option value="{{ $id }}" @selected((string)request('category_id')===(string)$id)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">وضعیت</label><select class="form-select" name="availability"><option value="">همه</option><option value="available" @selected(request('availability')==='available')>موجود</option><option value="unavailable" @selected(request('availability')==='unavailable')>ناموجود</option></select></div><div class="col-auto"><button class="btn btn-outline-primary">اعمال فیلتر</button></div>@if(request()->hasAny(['search','category_id','availability']))<div class="col-auto"><a class="btn btn-light" href="{{ route('products.index') }}">پاک کردن</a></div>@endif</form></div>
<div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'title','direction'=>$sort==='title'&&$direction==='asc'?'desc':'asc']) }}">محصول <i class="bi bi-arrow-down-up"></i></a></th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'code','direction'=>$sort==='code'&&$direction==='asc'?'desc':'asc']) }}">کد <i class="bi bi-arrow-down-up"></i></a></th><th>دسته</th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'weight','direction'=>$sort==='weight'&&$direction==='asc'?'desc':'asc']) }}">وزن <i class="bi bi-arrow-down-up"></i></a></th><th>اجرت</th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'availability','direction'=>$sort==='availability'&&$direction==='asc'?'desc':'asc']) }}">وضعیت <i class="bi bi-arrow-down-up"></i></a></th><th><a class="text-reset text-decoration-none" href="{{ request()->fullUrlWithQuery(['sort'=>'created_at','direction'=>$sort==='created_at'&&$direction==='asc'?'desc':'asc']) }}">تاریخ <i class="bi bi-arrow-down-up"></i></a></th><th class="text-start">عملیات</th></tr></thead><tbody>
@forelse($products as $product)<tr><td><div class="d-flex align-items-center gap-2">@if($product->main_image)<img class="thumb" src="{{ '/storage/'.ltrim($product->main_image, '/') }}" alt="">@else<div class="thumb text-center pt-3"><i class="bi bi-image"></i></div>@endif<a class="text-decoration-none text-dark fw-semibold" href="{{ route('products.show',$product) }}">{{ $product->title }}</a></div></td><td><code>{{ $product->code }}</code></td><td>{{ $product->category->name }}</td><td>{{ $product->weight ? number_format((float)$product->weight,3) : '—' }} {{ $product->weight ? $product->weight_unit : '' }}</td><td>{{ $product->wage_percentage !== null ? $product->wage_percentage.'٪' : '—' }}</td><td><span class="badge bg-{{ $product->availability === 'available' ? 'success' : 'secondary' }}-subtle text-{{ $product->availability === 'available' ? 'success' : 'secondary' }}">{{ $product->availability === 'available' ? 'موجود' : 'ناموجود' }}</span></td><td>{{ $product->created_at->format('Y/m/d') }}</td><td class="text-start text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="{{ route('products.show',$product) }}"><i class="bi bi-eye"></i></a> <a class="btn btn-sm btn-outline-primary" href="{{ route('products.edit',$product) }}"><i class="bi bi-pencil"></i></a> <form class="d-inline" method="POST" action="{{ route('products.destroy',$product) }}" data-confirm="محصول و تصاویر گالری آن حذف می‌شوند؛ کد آن دوباره استفاده نخواهد شد.">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="8" class="text-center py-5 text-muted">محصولی یافت نشد.</td></tr>@endforelse
</tbody></table></div>@if($products->hasPages())<div class="card-footer bg-white pt-3">{{ $products->links() }}</div>@endif</div>
@endsection
